apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyfin-instance
  namespace: argocd
spec:
  project: jellyfin
  source:
    chart: jellyfin
    repoURL: https://k8s-at-home.com/charts/
    targetRevision: 2.1.3
    helm:
      releaseName: sealed-secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: utils
  syncPolicy:
    automated:
      prune: false
      selfHeal: true