apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyfin-instance
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: media
  source:
    chart: jellyfin
    repoURL: https://k8s-at-home.com/charts/
    targetRevision: 9.3.0
    helm:
      # https://github.com/k8s-at-home/charts/blob/master/charts/stable/jellyfin/values.yaml
      values: |
        env:
          TZ: "America/New_York"
        persistence:
          config:
            enabled: true
            existingClaim: jellyfin-config
          media:
            enabled: true
            existingClaim: jellyfin-media
  destination:
    server: https://kubernetes.default.svc
    namespace: media
  syncPolicy:
    automated:
      prune: false
      selfHeal: true