apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: wolves-z.nfs
  resources:
    requests:
      storage: 10Ti
  volumeName: media
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: wolves-z.nfs
  resources:
    requests:
      storage: 10Ti
  volumeName: jellyfin-config