{{- range $project, $apps := .Values.inventory }}
  {{- range $_, $app := $apps }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $app }}
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: {{ $project }}
  source:
    repoURL: {{ $.Values.repo }}
    targetRevision: HEAD
    path: {{ printf "apps/%s/%s" $project $app }}
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ $project }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  {{- end }}
{{- end }}