{{- range $project, $_ := .Values.inventory }}
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ $project }}
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0" # this is default behavior
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: {{ $project }} Project
  sourceRepos:
  - '*'
  destinations:
  - namespace: {{ $project }}
    server: https://kubernetes.default.svc
---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0" # this is default behavior
  name: {{ $project }}
{{- end }}