{{- range $project, $_ := .Values.inventory }}
---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  name: {{ $project }}
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ $project }}
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: {{ $project }} Project
  sourceRepos:
  - {{ .Values.repo }}
  destinations:
  - namespace: {{ $project }}
    server: https://kubernetes.default.svc
{{- end }}