apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: webservers
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Example Project
  destinations:
  - namespace: webservers
    server: https://kubernetes.default.svc