apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-instance
  namespace: argocd
spec:
  project: utils
  source:
    chart: argo-cd
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 3.33.6
    helm:
      releaseName: argo-cd
      values: |
        server:
          extraArgs:
          - --insecure
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: false
      selfHeal: true