apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.2.5/manifests/install.yaml

configMapGenerator:
# https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/
- name: argocd-cm
  behavior: merge
  literals:
  - url="https://argocd.k8s.lab.reb.gg"
  - users.anonymous.enabled="false"
  - statusbadge.enabled="true"
# https://argo-cd.readthedocs.io/en/stable/operator-manual/server-commands/additional-configuration-method/
- name: argocd-cmd-params-cm
  behavior: merge
  literals:
  - server.insecure="true" # proxy will terminate tls