apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets-instance
  namespace: argocd
spec:
  project: utils
  source:
    chart: sealed-secrets
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    targetRevision: 2.1.3
    helm:
      releaseName: sealed-secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: sealed-secrets